local function run(msg, matches)
    if is_owner(msg) then
        return
    end
    local data = load_data(_config.moderation.data)
    if data[tostring(msg.to.id)] then
        if data[tostring(msg.to.id)]['settings'] then
            if data[tostring(msg.to.id)]['settings']['lock_badw'] then
                lock_fosh = data[tostring(msg.to.id)]['settings']['lock_badw']
            end
        end
    end
    local chat = get_receiver(msg)
    local user = "user#id"..msg.from.id
    if lock_fosh == "yes" then
        send_large_msg(chat, '🔴به دلیل فحاشی از گروه اخراج شدید')
        chat_del_user(chat, user, ok_cb, true)
    end
end
 
return {
  patterns = {
    "کس(.*)",
    "کص(.*)",
    "کث(.*)",
    "کسو(.*)",
    "kos(.*)",
    "Kos(.*)"
    "کس(.*)",
    "کون(.*)",
    "کـون(.*)",
    "کوون(.*)",
    "کووون(.*)",
    "ککون(.*)",
    "کیر(.*)",
    "ممه(.*)",
    "mame(.*)",
    "Mame(.*)",
    "پستون(.*)",
    "لاپا(.*)",
    "سکس(.*)",
    "لات(.*)",
    "منی(.*)",
    "اسپرم(.*)",
    "سیکتیر(.*)",
    "fuck(.*)",
    "Fuck(.*)",
    "قهبه(.*)",
    "بسیک(.*)",
    "بیناموس(.*)",
    "جنده(.*)",
    "اوبی(.*)",
    "obi(.*)",
    "Obi(.*)",
    "کونی(.*)",
    "بیشرف(.*)",
    "کس ننه(.*)",
    "ساک(.*)",
    "کیری(.*)",
    "خار کوسه(.*)",
    "ننه(.*)",
    "خواهرتو(.*)",
    "سکسی(.*)",
    "sex(.*)",
    "Sex(.*)",
    "کسکش(.*)",
    "سیک تیر(.*)",
    "گاییدم(.*)",
    "میگام(.*)",
    "تلمبه(.*)",
    "سینه(.*)",
    "کونده(.*)",
    "koonde(.*)",
    "Koonde(.*)",
    "ژووون(.*)",
    "زیر خواب(.*)",
    "میگامت(.*)",
    "migamet(.*)",
    "Migamet(.*)",
    "بسیک(.*)",
    "خواهرت(.*)",
    "مادر(.*)",
    "خارتو(.*)",
    "کونت(.*)",
    "koonet(.*)",
    "Koonet(.*)",
    "کوست(.*)",
    "Koset(.*)",
    "koset(.*)",
    "شورت(.*)",
    "سگی(.*)",
    "پدرسگ(.*)",
    "مادر جنده(.*)",
    "کیری(.*)",
    "kiri(.*)",
    "دول(.*)",
    "ننت(.*)",
    "nanat(.*)",
    "Nanat(.*)",
    "ابمو(.*)",
    "آبمو(.*)",
    "جق(.*)",
    "jaq(.*)",
    "Jaq(.*)",
    "jagh(.*)",
    "Jagh(.*)",
    "jaghi(.*)",
	"Jaghi(.*)",
    "shut up(.*)",
    "Shut up(.*)",
    "motherfucker,(.*)",
    "Motherfucker,(.*)",
    "sisterfucker(.*)",
    "Sisterfucker(.*)",
    "trollop(.*)",
    "Trollop(.*)",
    "whore(.*)",
	"Whore(.*)",
  "xxx(.*)",
  "Xxx(.*)",
  "xnxx(.*)",
  "Xnxx(.*)",
  "xvideo(.*)",
  "Xvideo(.*)",
  "ایکس ویدیو(.*)",
  "اکس ویدیو(.*)",
  "ایکس ویدئو(.*)",
  "اکس ویدئو(.*)",
  "برزر(.*)",
  "brazzer(.*)",
  "Brazzer(.*)",
  "xxlxx(.*)",
  "Xxlxx(.*)",
  "الکسیس(.*)",
  "alexis(.*)",
  "سوتین(.*)",
  "صوتین(.*)",
  "ثوتین.*)",
  "سووتین(.*)",
  "sootian(.*)",
  "Sootian(.*)",
  "sutian(.*)",
  "Sutian(.*)",
  "sotian(.*)",
  "Sotian(.*)",
  "suutian(.*)",
  "Suutian(.*)",
  "sootyan(.*)",
  "Sootyan(.*)",
  "شرت(.*)",
  "short(.*)",
  "Short(.*)",
  "کرست(.*)",
  "korset(.*)",
  "Korset(.*)",
  "corset(.*)",
  "Corset(.*)",
  "نوار بهداشتی(.*)",
  "navar behdashti(.*)",
  "Navar behdashti(.*)",
  "پریود(.*)",
  "periood(.*)",
  "Periood(.*)",
  "periuud(.*)",
  "Periuud(.*)",
  "period(.*)",
  "Period(.*)",
  "periud(.*)",
  "Periud(.*)",
  "بالدار(.*)",
  "baldar(.*)",
  "Baldar(.*)",
  "درز عقب(.*)",
  "darze aqab(.*)",
  "Darze aqab(.*)",
  "هرزه(.*)",
  "harze(.*)",
  "Harze(.*)",
  "فاحشه(.*)",
  "faheshe(.*)",
  "Faheshe(.*)",
  "پرن(.*)",
  "پرناستار(.*)",
  "پرنستار(.*)",
  "porn(.*)",
  "Porn(.*)",
  "pornstar(.*)",
  "Pornstar(.*)",
  "daf(.*)",
  "Daf(.*)",
  "داف(.*)",
  "کس گشاد(.*)",
  "kos goshad(.*)",
  "Kos goshad(.*)",
  "کون گشاد(.*)",
  "koon goshad(.*)",
  "Koon goshad(.*)",
  "pare(.*)",
  "jeret(.*)",
  "جرت(.*)",
  "ساک ریز(.*)",
  "sak riz(.*)",
  "Sak riz(.*)",
  "کس لیس(.*)",
  "کسلیس(.*)",
  "کص لیس(.*)",
  "کث لیس(.*)",
  "koslis(.*)",
  "Koslis(.*)",
  "کسباز(.*)",
  "کصباز(.*)",
  "کثباز(.*)",
  "kosbaz(.*)",
  "Kosbaz(.*)",
  "کس پرور(.*)",
  "kos parvar(.*)",
  "کیر دراز(.*)",
  "کیر کلفت(.*)",
  "kir deraz(.*)",
  "kir koloft(.*)",
  "Kir koloft(.*)",
  "Kir deraz(.*)",
  "بخورش(.*)",
  "bokhoresh(.*)",
  "mikonamet(.*)",
  "Mikonamet(.*)",
  "میکنمت(.*)",
  "حاملت(.*)",
  "hamelat(.*)",
  "Hamelat(.*)",
  "مامانتو(.*)",
  "mamaneto(.*)",
  "Mamaneto(.*)",
  "خواهرتو(.*)",
  "khahareto(.*)",
  "Khahareto(.*)",
  "خوارتو(.*)",
  "khareto(.*)",
  "Khareto(.*)",
  "ننتو(.*)",
  "nanato(.*)",
  "Nanato(.*)",
  "اجیتو(.*)",
  "ajito(.*)",
  "Ajito(.*)",
  "ولدزنا(.*)",
  "ولد زنا(.*)",
  "valadzena(.*)",
  "valade zena(.*)",
  "Valade zena(.*)",
  "جنده زاده(.*)",
  "jende zade(.*)",
  "Jende zade(.*)",
  "کسخل(.*)",
  "کصخل(.*)",
  "کثخل(.*)",
  "کسمیخ(.*)",
  "koskhol(.*)",
  "koskhol(.*)",
  "kosmikh(.*)",
  "kos mikh(.*)",
  "Kos mikh(.*)",
  "Kosmikh(.*)",
  "Koskhol(.*)",
  "Koskhol(.*)",
  "بلا كرامة(.*)",
  "بلا كرامه(.*)",
  "کس أختك(.*)",
  "کس أمك(.*)",
  "فاحشة(.*)",
  "كلب الأب(.*)",
  "كلب الأم(.*)",
  "حمار(.*)",
  "غبي(.*)",
  "قذر(.*)",
  "نجس(.*)",
  "لص(.*)",
  "مدمر(.*)",
  "متصلب(.*)",
  "bk_k_bk(.*)",
  "bk k bk(.*)",
  "bk(.*)",
  "bt(.*)",
  "bt k bt(.*)",
  "bt_k_bt(.*)",
  "www.porn.com(.*)",
  "www.pornhub.com(.*)",
  "www.youporn.com(.*)",
  "www.xvideos.com(.*)",
  "www.redtube.com(.*)",
  "www.tnaflix.com(.*)",
  "www.pornolaba.com(.*)",
  "www.ixxx.com(.*)",
  "www.xnxx.com(.*)",
  "theporndude.com(.*)",
  "www.pornktube.com(.*)",
  "mashable.com(.*)",
  "wanted-porn.com(.*)",
  "www.pornhub.com(.*)",
  "www.17sexvideo.com(.*)",
  "www.youx.xxx(.*)",
  "www.teenpornsex.info(.*)",
  "www.xnxx.com(.*)",
  "www.tnaflix.com(.*)",
  "www.usexvideos.com(.*)",
  "www.sexvid.xxx(.*)",
  "xmissy.nl(.*)",
  "www.redtube.com(.*)",
  "www.bangkokpost.com(.*)",
  "xnxx.com(.*)"
  },
  run = run
}